### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by Ghostenshell** [AutomateThePlanet/Design-Patterns-for-High-Quality-Automated-Tests-CSharp-Edition#1]
Thank you for the advanced tutorial.  I'm in between novice and advanced programmer so bare with me.  I am having an issue withChapter 2.  I don't know if this was done on purpose or its there for me to debug.

The issue is lines 67 and 136 of the first folder.  [Assert.AreEqual("114.00€", totalSpan.Text);
](url)
95 Euros are expected is the error.  When I correct this the next test fails.  Any suggestions on how to fix this?

**Comment by angelovstanton** [comment]
Yes, from 1-3 chapter, it is expected the tests to fail on random since they are flaky. In chapter 3, they should be more or less more stable. The tests till chapter 3 are depending on each other, which was the intent to show that this is a bad practice. I think I mentioned it somewhere, but I will take this as feedback, and in a future release, I will address it more clearly.

**Comment by Ghostenshell** [comment]
Thanks for the response.
You did address flaky but this is a new term and didn't stick right away.  I am starting to understand now as I debug.
Before I close this I wanted to say that I took this as a great way to debug the program.  For example.  I couldn't figure out why it wasn't picking the "orderNumber".  Since the page doesn't remain static the programmer would have to go into the code and swap out the old Xpath for a new one.  
Thanks for your time.
